### ISSUE TITLE
API call failed 401

### ISSUE THREAD

**Issue by neander-squirrel** [busyorg/steemconnect#15]
I am trying to make a page where I can vote with set amount of voting power.

I have successfully uploaded the example file (examples/index.html) from your library to 000webhost and I am able to log in on steemConnect but it's always returning with error 401 after log in.

Please check my code on https://neander-squirrel.000webhostapp.com and tell me what I am doing wrong.

Thank you

**Comment by nil1511** [comment]
Hello neander,
Have you set the origin to `https://neander-squirrel.000webhostapp.com`. From error, it seems origin is not allowed. Origin should be a full domain name not route.

**Comment by neander-squirrel** [comment]
Hi Nil,
I set it to http://neander-squirrel.000webhostapp.com/index.html
so as my redirect url.

**Comment by nil1511** [comment]
Set Origin to `https://neander-squirrel.000webhostapp.com` It should not have any path just domain

**Comment by neander-squirrel** [comment]
I did it. It is still error 401.

**Comment by nil1511** [comment]
<img width="632" alt="screen shot 2017-06-27 at 10 31 42 am" src="https://user-images.githubusercontent.com/2058170/27571504-dca769e6-5b23-11e7-9181-b17e730a13f0.png">
Now it is showing this after login.

**Comment by neander-squirrel** [comment]
not for me:D
Can it be something with my key?
Which key I should use to login?

**Comment by nil1511** [comment]
private posting wif or password( it will automatically convert and use private posting wif). 
You need to authorize the app by [login](https://steemconnect.com/authorize/@neander-squirrel?redirect_url=https://neander-squirrel.000webhostapp.com/index.html)

**Comment by neander-squirrel** [comment]
I'm doing that. 401 is the only thing i see.
i even tried from mobile

**Comment by neander-squirrel** [comment]
do i need some setup on my pc?

**Comment by nil1511** [comment]
No setup needed on PC. It works fine with default browser setting

**Comment by neander-squirrel** [comment]
cookies:)

**Comment by neander-squirrel** [comment]
thank you for your help. it is working now:)
