### ISSUE TITLE
Unable to authenticate after successfully logging in (401 error)

### ISSUE THREAD

**Issue by stephanmullerNL** [busyorg/steemconnect#17]
I've implemented steemconnect in my Angular 4 app and try to use it to check if a user is authorized. For ease of testing I simply added this code to the onInit method of my main controller. The app literally does nothing else than try to authorize the user and provide a link to the steemconnect login page 

```
ngOnInit() {
        steemconnect.init({
            app: 'pilcrow'
        });

        // for the link in the page
        this.url = steemconnect.getLoginURL(); 

        steemconnect.isAuthenticated((err, result) => {
            this.loggedIn = !!result;

            if (err) {
                this.message = err;
                console.log('error!', err);
            } else {
                this.message = `Logged in as ${result.username}`;
                console.log('authorized', result);
            }
        });
});
```

Initially this gives me a `Steem Connect API call failed with 401` because I'm not logged in yet. When I click the login link and log in to steemconnect, I'm redirected back to my app. The code runs again, but this time too I get a 401 error on `https://steemconnect.com/api/@pilcrow/verify?`. 

If I open that url directly in a new tab, I do get a proper JSON response telling me I'm logged in. Is there some CORS issue going on here?

The settings in my steemconnect app are as follows.

> Author: pilcrow
> Permissions: [all checked]
> 
> Allowed origins:
> http://localhost:4200
> http://localhost:4200/login
> http://kanzeon.litso.com
> 
> Allowed redirect urls:
> http://localhost:4200/
> http://kanzeon.litso.com/
> 
> [Development mode]

I tried changing the baseURL to `https://dev.steemconnect.com/` but that results in the error `{ error: "App not found" }`.

When I change the baseURL to http instead of https, I get the following error in my console:

>Fetch API cannot load http://steemconnect.com/api/@pilcrow/verify?. Redirect from 'http://steemconnect.com/api/@pilcrow/verify?' to 'https://steemconnect.com/api/@pilcrow/verify?' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

All of the above is exactly the same on both http://localhost:4200/ and http://kanzeon.litso.com/ (you can see the issue there right now). Neither use https for now, I do plan on implementing that on my server soon but for now I'd just like to get a development environment running.

All the relevant code can also be seen at https://github.com/stephanmullerNL/kanzeon/tree/feature/login. Ignore the login route and component, they are not used for this example.

Can anyone point me in the right direction?

**Comment by stephanmullerNL** [comment]
Update: I figured out that I had to manually register at dev.steemconnect.com (it would be really nice if at least _some_ documentation was available on the website at all). After I did that, I had to give my own app permissions again, and I noticed that because i didn't give a redirect url it failed to redirect me back to my app properly.

I added a redirectURL as well, but still nothing has changed regarding the original issue.

**Comment by bonustrack** [comment]
The subdomain dev.steemconnect.com is used a staging deployment by our team to test update and is not supposed to be used in production. We just disabled it to avoid confusion. You can use steemconnect.com directly.

About login I've not been able to reproduce the issue, I tried using http://kanzeon.litso.com and changing the `redirect_uri` to http://kanzeon.litso.com/ and it's been working fine for me. See here: https://user-images.githubusercontent.com/16245250/28354853-b4c21376-6c8b-11e7-841d-968411b61a49.png

I could be a limitation from the browser. Can you tell me which browser you are using? And if you have 3rd party cookie enabled like this (Firefox): https://user-images.githubusercontent.com/16245250/28355273-7d039250-6c8d-11e7-8d6d-ca8727e722d3.png

**Comment by stephanmullerNL** [comment]
Oh huh, that is interesting. Thanks for the effort, I'm going to see if I can manage to get it working too. 

I use chrome, and I tried it in n incognito tab too to prevent my extensions from getting in the way. I'll see if another browser makes a difference.

**Comment by stephanmullerNL** [comment]
@bonustrack Turns out I had disabled third party cookies, so turning those on solved it. Thanks again for your help.
